### ISSUE TITLE
Warning message active all pages since update.

### ISSUE THREAD

**Issue by husDOM** [JayWood/content-warning-v3#20]
Good Day Sir,

I have been using your plugin now for some time on two separate websites with much success.  The plugin has been wonderful.  Recently I have been experiencing an issue with some but not all of my members.  When they select "enter' the warning will disappear but reappear every page change.  The users discussing this with me this evening are 2 Safari users and 1 Chrome user.  The Chrome user selected F5 and said that it did resolve his issue.  I am experiencing this issue on both websites.

www.littlekaninchen.com
www.husdom.com

I have deactivated the plugin twice with no positive results.  

I currently have the plugin deactivated for both of these sites but would be happy to activate them if you need to see the issue.  I like this plugin very much and would like to know when it is working properly.

I should also mention that I have recently changed servers and have been experiencing other issues site wide so I am not 100% positive that this is an issue with the plugin as it may be with my server or settings.

Best wishes,

Mr Fox

**Comment by JayWood** [comment]
Unfortunately I'm unable to replicate that, of course, because my server isn't yours.

I have an itch that this may be a portion of the issue.  If the JS i'm loading in the plugin is getting this same issue, it would explain why the cookies aren't getting set, etc..
![cloudflare-issues](https://cloud.githubusercontent.com/assets/2303074/5841479/4adfb924-a16b-11e4-8a15-fa342305b45d.png)

I would say start with that issue first, or, at the very least, enable the CW plugin, and set cloudflare to development mode ( temporarily disabling it ) and get your viewers to try again.

If you can get me a gist of the sourcecode of the page that is re-displaying the issue that'd be great as well, so I can tell if the flag is being set in the localized javascript variables or not.  You'll need to verify you have a cookie for that page as well.

Side Note:
The cookie logic was completely re-written and I'm now using javascript instead of PHP, so caching shouldn't affect the cookie setting/getting.  But I'll know more once I can get you to shoot me that source code of the problem page.

**Comment by husDOM** [comment]
Jay,

Thank you for your quick response to my query.  This may be a bit over my head at the time and I will probably disable the plugin for some time.  When I have enough time to give this proper attention may I contact you again for some guidance?

Best wishes, 

Mr Fox

**Comment by JayWood** [comment]
Feel free to contact me anytime, for now I'll close this, feel free to comment on it once you have time.
