### ISSUE TITLE
Cookies are not being saved

### ISSUE THREAD

**Issue by katietdesign** [JayWood/content-warning-v3#21]
Hello!
The plugin was working great while I had it on my testing server, but then once I moved the Wordpress site to my client's server, the plugin is not working as it was before. I deactivated/activated it, as well as uninstalled and re-installed without any luck.

Settings:
Sitewide: Unchecked
Home Page: Checked
Misc. Pages: Unchecked
Cookie Life: Currently 10 days, but the warning shows up every time no matter what the number here says.

The site is not set to a home page, but the latest posts page. 

When you first go to the site you will see the warning as intended. Then if you refresh or click the home button it shows again. If you click NO I am not 18 yrs old, it will take you to Google as intended, but then if you revisit the site it will show the warning again. I would like for the warning to show on all pages but I have disabled that for now so that the site is somewhat usable while I try and solve this issue.

This is happening in Chrome, Firefox, IE, and Android native browser (maybe more but these are the ones I've tested).

Website:
http://www.optimalvapor.com

Thank you for any help you can provide. I really like this plugin and it is the best that I've found for the purpose it serves. 

Let me know if I can provide more information.

**Comment by JayWood** [comment]
First off, thank you for keeping the plugin up so I can see what was going on.

It appears that the constant I'm using to set the cookie path is returning /wordpress/ as your site's cookie path.
![wrong_path](https://cloud.githubusercontent.com/assets/2303074/6204740/590399be-b523-11e4-81ff-3453e907a1d5.png)

The path should be set to `/` not `/wordpress/`, which is why you're getting the popup every time.  I assume you may have your WordPress installed in it's own directory?  If so [this link](http://polevaultweb.com/2014/02/wordpress-own-directory-cookies/) should help for now.  

If not, is your site a multi-site of some sort?

**Comment by katietdesign** [comment]
You're awesome!! 
I have Wordpress in it's own directory. (Which is why it was working while on my test server but quit working when I moved it to my client's site into it's own directory.)

For future reference in case you have anyone else with this problem:
The article you gave me helped, but when I inserted the code into my wp-config.php file, it created a redirect loop when navigating to wp-login or wp-admin.

So I found the following code at: https://tommcfarlin.com/resolving-the-wordpress-multisite-redirect-loop/

define('ADMIN_COOKIE_PATH', '/');
define('COOKIE_DOMAIN', '');
define('COOKIEPATH', '');
define('SITECOOKIEPATH', '');

I inserted this above the "That's all, stop editing! Happy blogging." part. 

And now the plugin works exactly as it should and I can still access wp-admin. 

THANK YOU for your help and your quick response! And for this awesome plugin! :)
