### ISSUE TITLE
Check WooCommerce integration

### ISSUE THREAD

**Issue by JayWood** [JayWood/content-warning-v3#33]
I'm un-sure if this will work with the WooCommerce product and product cat's post type, but it DEFINITELY should.

**Comment by jimenezfl** [comment]
Im using Storefront theme with WooCommerce.  warning box is not working.  I dont receivve any errors through Chrome Debug tools.  the theme contains  <?php wp_head(); ?>  not wp_header() exactly.  Does content warning need exact function name?

**Comment by JayWood** [comment]
Ensure your theme also runs `wp_footer()` in the footer file. And no, `wp_head()` is the right method.

**Comment by 95CivicSi** [comment]
I have tested with WooCommerce 2.5.5 and WooFramework 6.2.6 using the Storefront 1.6.1 theme and MyStyle 1.3.11.  Everything works as expected,

**Comment by JayWood** [comment]
@95CivicSi Would you care to elaborate on the tests?

**Comment by 95CivicSi** [comment]
Tests involved checking entry stops at all pages including product pages, cart, and checkout.  Test were performed on Google Chrome 49.0.2623.112 on a Windows 10 machine.   Entry stop was tested by opening an incognito window and pasting URLs into the address bar.

When a user is signed in, there is no entry stop, even if a cookie has not been generated or contains "false".  Age gate does not appear on wp-login.php, (I consider this expected behavior).

After clicking the entry button on the age gate, user experience was tested by attempting to place items in a cart and perform checkout operations with cash payment and paypal payments.  Paypal payments were tested with a sandbox account.  User experience was tested with a guest account and a logged in customer.  There was no differences in the user experience (in either situation).  Cart and checkout function operated as normal.

If you would like, I can test with Edge, IE, and Firefox tomorrow.

**Comment by JayWood** [comment]
@95CivicSi Great, for now I'll close this, seems like it works as expected ie. not interfering with normal WC operations. I honestly don't believe QA needs to happen on all browsers, I'm pretty sure the only thing that will differ, if at all, will be design/css related data.

Of course, feel free to re-open this if for some reason something pops up. And thanks again for your help :+1:
